\---
title: "STA108 Final Project"
author: "Madalyn Papenfuss, Sung Ah Lee, Chang, Brian"
date: "2023-12-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("cli")

library("caret")
install.packages("caret")
install.packages("cli")

library(caret)
```

```{r}
data = read.csv("heart_disease_health_indicators_BRFSS2015.csv")
# colnames = HeartDiseaseorAttack, HighBP, HighChol, CholCheck, BMI, Smoker, Stroke, Diabetes, PhysActivity, Fruit, Veggies, HvyAlcoholConsump, AnyHealthcare, NoDocbcCost, GenHlth, MentHlth, PhysHlth, DiffWalk
head(data)
#col_name = c(1,2,3,5,6,7,8,9)
#data = data[,col_name]
#interested in col: HeartDiseaseorAttack, HighBP, HighChol, BMI, Smoker, Stroke, Diabetes, PhysActivity (first 8 col)
```

```{r}
# creating test and train data
set.seed(13)
train_index <- sample(1:nrow(data), 0.5 * nrow(data))  # 50% for training 
train_data <- data[train_index, ]
test_data <- data[-train_index, ]
head(test_data)
#WILL CHANGE TO K-FOLD cv

```

```{r}
# Using train_data to create our model
logreg=glm(HeartDiseaseorAttack ~ HighBP + HighChol + CholCheck + BMI + Smoker + Stroke + Diabetes + PhysActivity + Fruits + Veggies + HvyAlcoholConsump + AnyHealthcare + NoDocbcCost + GenHlth + MentHlth + PhysHlth + DiffWalk + Sex + Age + Education + Income, data = train_data, family = binomial) #which variables are significant?

#significant variables = 
## (Intercept)       -7.7828371  0.1424933 -54.619  < 2e-16 ***
# HighBP             0.5238218  0.0249983  20.954  < 2e-16 ***
# HighChol           0.6099891  0.0231388  26.362  < 2e-16 ***
# CholCheck          0.4037878  0.0901655   4.478 7.52e-06
# Smoker             0.3481076  0.0221743  15.699  < 2e-16 ***
# Stroke             0.9670444  0.0349096  27.701  < 2e-16 ***
# Diabetes           0.1414394  0.0126559  11.176  < 2e-16 ***
# HvyAlcoholConsump -0.2474005  0.0546589  -4.526 6.00e-06 ***
# NoDocbcCost        0.2767829  0.0376501   7.351 1.96e-13 ***
# GenHlth            0.4770993  0.0133503  35.737  < 2e-16 ***
# DiffWalk           0.3139449  0.0272785  11.509  < 2e-16 ***
# Sex                0.7463776  0.0225979  33.029  < 2e-16 ***
# Age                0.2633630  0.0051587  51.052  < 2e-16 ***
# Income            -0.0461303  0.0059884  -7.703 1.33e-14 ***
logreg2 = glm(HeartDiseaseorAttack ~ HighBP + HighChol + CholCheck + Smoker + Stroke + Diabetes + HvyAlcoholConsump + NoDocbcCost + GenHlth + DiffWalk + Sex + Age + Income, data = train_data, family = binomial)
summary(logreg2)
```
```{r}

  
```

```{r}
# using logreg2 to predict test_data
prediction <- predict(logreg2, test_data, type = "response")
predicted_classes <- ifelse(prediction > 0.5, 1, 0)
confusion_matrix <- print(table(test_data$HeartDiseaseorAttack, predicted_classes))
print(sum(diag(confusion_matrix)) / sum(confusion_matrix))
```

```{r}
#plotting in R
#logregmodel = glm(HeartDiseaseorAttack ~ HighBP + HighChol + CholCheck + Smoker + Stroke + Diabetes + HvyAlcoholConsump + NoDocbcCost + GenHlth + DiffWalk + Sex + Age + Income, data = train_data, family = binomial)


par(mfrow = c(1, 1), mar = c(4, 4, 2, 1))
#HIGH BP
barplot(table(train_data$HighBP), col = c("tomato2", "darkblue"), beside = T, names.arg = c("No High Blood Pressure", "High Blood Pressure"), main = "High Blood Pressure Distribution", ylab = "Frequency", sub="Indicates if the person has been told by a health professional \nthat they have High Blood Pressure.")
#HIGH CHOL
barplot(table(train_data$HighChol), col = c("tomato2", "darkblue"), beside = T, names.arg = c("No High Cholestrol", "High Cholestrol"), main = "High Cholestrol Distribution", ylab = "Frequency", sub="Indicates if the person has been told by a health professional that they have \nHigh Blood Cholesterol.")
# CholCheck
barplot(table(train_data$CholCheck), col = c("tomato2", "darkblue"), beside = T, names.arg = c("No Cholesterol Check", "Yes Cholesterol Check"), main = "Cholesterol Check Distribution", ylab = "Frequency", sub = "Indicates if the person has their cholesterol levels checked \nwithin the last 5 years.")
#Smoker
barplot(table(train_data$Smoker), col = c("tomato2", "darkblue"), beside = T, names.arg = c("No Smoker", "Smoker"), main = "Smoker Distribution", ylab = "Frequency", sub = "Indicates if the person has smoked at least 100 cigarettes.")
#Stroke
barplot(table(train_data$Stroke), col = c("tomato2", "darkblue"), beside = T, names.arg = c("No Stroke History", "Stroke History"), main = "Stroke Distribution", ylab = "Frequency", sub = "Indicates if the person has a history of stroke.")
# Diabetes
barplot(table(train_data$Diabetes), col = c("tomato2", "green","darkblue"), beside = T, names.arg = c("No Diabetes", "Pre-Diabetes", "Diabetes"), main = "Diabetes Distribution", ylab = "Frequency")
# HvyAlcoholConsump
barplot(table(train_data$HvyAlcoholConsump), col = c("tomato2", "darkblue"), beside = T, names.arg = c("No Heavy Alcohol Consumption", "Heavy Alcohol Consumption"), main = "Heavy Alcohol Consumption Distribution", ylab = "Frequency", sub = "Indicates if the person has more than 14 drinks per week.")
# NoDocbcCost
barplot(table(train_data$NoDocbcCost), col = c("tomato2", "darkblue"), beside = T, names.arg = c("Did not experience", "No Doctor Visit because of Cost"), main = "No Doctor Because of The Cost", ylab = "Frequency", sub= "Indicates if the person wanted to visit a doctor within the past 1 year \nbut couldn’t, due to cost.")
# DiffWalk
barplot(table(train_data$DiffWalk), col = c("tomato2", "darkblue"), beside = T, names.arg = c("No Difficulty Walking", "Difficulty Walking"), main = "Difficulty Walking Distribution", ylab = "Frequency", sub = "Indicates if the person has difficulty while walking or climbing stairs.")
# Sex
barplot(table(train_data$Sex), col = c("tomato2", "darkblue"), beside = T, names.arg = c("Female", "Male"), main = "Sex Distribution", ylab = "Frequency")
# Age
color_gradient <- colorRampPalette(c("tomato2", "darkblue"))
colors.age <- color_gradient(13)
barplot(table(train_data$Age), col = colors.age, beside = T, names.arg = c("18-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80+"), las = 2, horiz = T, main = "Age Distribution", xlab = "Frequency", cex.names = 0.8)
# Income
colors.Income <- color_gradient(8)
barplot(table(train_data$Income), col = colors.Income, beside = T, names.arg = c("$10,000", "$20,000", "$30,000", "$40,000", "$50,000", "$60,000", "$70,000", "$75,000+"), main = "Income Distribution", cex.names=0.9, las = 2, horiz = T, xlab = "Frequency")
# GenHlth
colors.GenHlth <- color_gradient(5)
barplot(table(train_data$GenHlth), col = colors.GenHlth, beside = T, names.arg = c("Excellent", "-", "Moderate", "-", "Poor"), main = "General Health Distribution", las = 2, horiz = T, xlab = "Frequency")
```

```{r}
#age of people with heart attacks vs age of people without heart attacks
data0 = subset(data, HeartDiseaseorAttack<1 )
data1 = subset(data, HeartDiseaseorAttack >= 1 )
boxplot(data0$Age,data1$Age, names.arg=c("Age of people without Heart Attacks", "Age of people with Heart Attacks"))

boxplot(list(data0$Age, data1$Age),  col = c("tomato2", "darkblue"), y.name = c("18-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75-79"), names = c("No Heart Attack", "Heart Attack"), xlab = "Heart Attack Status", ylab = "Age", main = "Boxplot of Age by Heart Attack Status") #outliers for young age and heart attacks
mean(data0$Age) #7.813858
mean(data1$Age) #10.13121, older age

# boxplot with names parameter for labels 
boxplot(list(data0$GenHlth, data1$GenHlth),  col = c("tomato2", "darkblue"), names = c("No Heart Attack", "Heart Attack"), xlab = "Heart Attack Status", ylab = "General Health", main = "Boxplot of General Health by Heart Attack Status")
mean(data0$GenHlth) #2.422369
mean(data1$GenHlth) #3.367555, older age

boxplot(list(data0$Income, data1$Income),  col = c("tomato2", "darkblue"), names = c("No Heart Attack", "Heart Attack"), xlab = "Heart Attack Status", ylab = "Income", main = "Boxplot of Income by Heart Attack Status")
mean(data0$Income) #6.14805
mean(data1$Income) #5.148161, older age

#INCOME of people with heart attacks vs INCOME of people without heart attacks

#GEN Health of people with heart attacks vs GEN Health of people without heart attacks
```


```{r}
cor_matrix = cor(data[,c("Education", "Income")]);cor_matrix
cor_matrix = cor(data[,c("GenHlth", "MentHlth", "PhysHlth")]);cor_matrix
```


maybe matrix graph

